version: '2'
services:
  elasticsearch:
    image: "noeliai/imdb:version2"
    hostname: "elasticsearch"
    container_name: elasticsearch-docker_
    environment:
      - "discovery.type=single-node"
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin=https://app.elasticvue.com, http://cerebro:9000
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD", "curl", "-u", "elastic:searchPathRules", "-f", "localhost:9200" ]
      interval: 30s
      retries: 10
  cerebro:
    image: lmenezes/cerebro
    container_name: cerebro_
    hostname: "cerebro"
    ports:
      - 9000:9000
    command:
      - -Dhosts.0.host=http://elasticsearch:9200
  imdbapi:
    container_name: imdbApi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      elasticsearch:
        condition: service_healthy